# Project information
site_name: 'Evinda Summary'
site_description: 'Summary of Web Mining contains: crawling, preprocessing, modeling and evaluation'
site_author: 'evindawidiacahyaningrum'
site_url: 'https://evinda170093.github.io/'

# Copyright
copyright: '&copy; 2021 evindawidia'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/evinda170093/evinda170093.github.io'
edit_url: 'https://github.com/evinda170093/evinda170093.github.io'

# Configuration
docs_dir: 'docs_sample'
theme:
  name: 'material'
  language: 'en'
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  palette:
    primary: 'teal'
    accent: 'teal'
  features:
    - tabs
  # icon:
  #   logo: 'elogo'
  # favicon: 'assets/images/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: '_'

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML'
extra_css:
  - 'assets/css/custom.css'
extra:
  manifest: 'manifest.json'
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/evindawidia'
    - icon: 'fontawesome/brands/instagram'
      link: 'https://instagram.com/evindawidiacahya'

# Page tree
nav:
  - 'Summary of Web-Mining': 'index.md'
  - 'Crawling': 'crawling.md'
  - 'Text Preprocessing': 'text-preprocessing.md'
  - 'Modelling': 'modelling.md'
  - 'Evaluation': 'evaluation.md'
